from abc import ABC, abstractmethod
from typing import Optional, Any

class BaseStorageAdapter(ABC):
    @abstractmethod
    async def save_archive_metadata(self, user_id: int, item_type: str, metadata: dict) -> int: ...
    @abstractmethod
    async def get_storage_usage(self, user_id: int) -> dict: ...
    @abstractmethod
    async def cleanup_expired(self, user_id: int, retention_days: int) -> int: ...
    @abstractmethod
    async def check_quota(self, user_id: int) -> bool: ...
